# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  branches:
    include:
      - master
      - develop
      - release/*

trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - hotfix/*
      - feature/*

  paths:
    exclude:
    - spec/src/main/resources/apigeeConfig.yaml
    - spec/src/main/resources/azure-MAMCLI.yml
    - spec/src/main/resources/swagger.yml

resources:
  repositories:
    - repository: importsbuildtemplate
      type: github
      name: Maersk-Global/imports-build-templates
      ref: refs/heads/main
      endpoint: ADOtoGitHub
    - repository: BDTemplateRepo
      type: github
      name: Maersk-Global/DOT-AzureDevops-CICD-templates
      ref: refs/heads/master # use master branch as default
      endpoint: ADOtoGitHub
    - repository: PolarisTemplateRepo
      type: github
      name: Maersk-Global/DOT-AzureDevops-CICD-templates
      ref: refs/heads/master # use master branch as default
      endpoint: ADOtoGitHub
    - repository: self

variables:
  tag: '$(Build.BuildNumber)'
  ImageName: ohm/ohm-sample
  NexusConnection: NexusMaerskDevNetRW-OH-Modernization

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - template: polaris.template.yml@PolarisTemplateRepo
        parameters:
          polarisScanBranch: main
          nexusMaven: true
          javaVersion: '11'

      - job: Build
        displayName: Build
        steps:
          - template: imports_api_build_template.yml@importsbuildtemplate
            parameters:
              SKIP_SONAR: false
              NEXUS_MAERSK_DEV_NET_CONNECTION: $(NexusConnection)
              SONAR_QUBE_CONNECTION: ado_sonar_maerskdev_net_token-OH-Modernization

      - job: ComponentTest
        dependsOn:
          - Build
        continueOnError: false
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: component-testing-pipeline-template.yml@importsbuildtemplate
            parameters:
              COMPONENT_TEST_REPORT_TITLE: ohm-sample
              SKIP_COMPONENT_TEST: false
              NEXUS_MAERSK_DEV_NET_CONNECTION: $(NexusConnection)

      - job: BlackduckScan
        dependsOn:
        - Build
        condition: or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'],'refs/heads/release/'), startsWith(variables['Build.SourceBranch'],'refs/heads/hotfix/'))
        steps:
        - task: MavenAuthenticate@0
          displayName: Nexus MaerskDevNet Authentication
          inputs:
            mavenServiceConnections: $(NexusConnection)

        - template: blackduck.template.yml@BDTemplateRepo

      - job: DockerHelm
        dependsOn:
        - IntegrationTest
        - BlackduckScan
        condition: in(dependencies.BlackduckScan.result, 'Succeeded', 'Skipped')
        steps:
          - template: docker_build_push_helm_values_template.yml@importsbuildtemplate
            parameters:
              IMAGE_NAME: $(ImageName)
              TAG_NUMBER: $(tag)
              ACR_SERVICE_CONNECTION: acr-ohm-connection

     - job: PublishPostDeployTestArtifacts
       dependsOn: IntegrationTest
       condition: in(dependencies.BlackduckScan.result, 'Succeeded', 'Skipped')
       pool:
         vmImage: 'ubuntu-latest'
       steps:
         - template: imports_post_deployment_test_template.yml@importsbuildtemplate
